"""Add review system

Revision ID: 3b2f012964de
Revises: e881401cd3f3
Create Date: 2024-10-16 15:11:13.198489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b2f012964de'
down_revision = 'e881401cd3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipa_app')
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_review_timestamp')
        batch_op.drop_constraint('review_app_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'app', ['app_id'], ['id'])
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('review_app_id_fkey', 'ipa_app', ['app_id'], ['id'])
        batch_op.create_index('ix_review_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    op.create_table('ipa_app',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('compatibility', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icon_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ipa_app_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ipa_app_pkey')
    )
    # ### end Alembic commands ###
